### PR TITLE
Add custom max buffers for bouncing

### PR DESCRIPTION
**Pull request by robtize**

### CODE REVIEW

**Comment by igorski** [comment]
What problem is this code solving ? You can indeed increase the buffer size for each render iteration of the bounce operation, but would there be much performance gain ? When bouncing the audio, audio is rendered as fast as possible, the renderer does iterate totalSize / bufferSize iterations to achieve this but the cost of these iterations should be negligible. Also keep in mind that large buffer sizes will occupy a lot of memory (e.g. passing a buffer size equal to the composition length requires the allocation an equal amount of memory).

**Comment by robtize** [comment]
Hey Igor!

The reason I did this is so we don’t have to have multiple wave files after
a rendering. If you recommend another way around this please do share.

Thanks!

-Robert

**Comment by igorski** [comment]
I see (or rather: I remember what the idea was here! :) ). So in your scenario you determine whether or not the available space on the device is sufficient for the composition in its entirety, right ?

In that case I say this is worthy of a merge. The correct solution would however be to concatenate all fragmented recordings into a single one as quite frankly, it's a bit strange behaviour :)

**Comment by robtize** [comment]
Yes! this is correct. however i can try the concatenating approach as well thanks again as always igor!

**Comment by igorski** [comment]
Overcoming the issue where separate .wav files are generated at the cost of consuming more memory. Follow up #59 has been created.

**Pull request merged**
